version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: easy_chores_db
    environment:
      POSTGRES_DB: easy_chores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: easy_chores_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
